# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_param chipscope.maxJobs 2
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/malak/sites/addproject/caeser_cipher_with_paths/caeser_cipher_with_paths.cache/wt [current_project]
set_property parent.project_path /home/malak/sites/addproject/caeser_cipher_with_paths/caeser_cipher_with_paths.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/malak/sites/addproject/caeser_cipher_with_paths/caeser_cipher_with_paths.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/malak/sites/addproject/caeser_cipher_with_paths/caeser_cipher_with_paths.srcs/sources_1/imports/imports/FPGA/AHBLITE_SYS.v
  /home/malak/sites/addproject/caeser_cipher_with_paths/caeser_cipher_with_paths.srcs/sources_1/imports/imports/AHB_VGA/AHBVGASYS.v
  /home/malak/sites/addproject/caeser_cipher_with_paths/caeser_cipher_with_paths.srcs/sources_1/imports/new/FSM.v
  /home/malak/sites/addproject/caeser_cipher_with_paths/caeser_cipher_with_paths.srcs/sources_1/imports/sources_1/imports/keyboard/PS2Receiver.v
  /home/malak/sites/addproject/caeser_cipher_with_paths/caeser_cipher_with_paths.srcs/sources_1/imports/sources_1/new/caeserEncoder.v
  /home/malak/sites/addproject/caeser_cipher_with_paths/caeser_cipher_with_paths.srcs/sources_1/imports/sources_1/imports/imports/AHB_VGA/counter.v
  /home/malak/sites/addproject/caeser_cipher_with_paths/caeser_cipher_with_paths.srcs/sources_1/imports/sources_1/imports/keyboard/debouncer.v
  /home/malak/sites/addproject/caeser_cipher_with_paths/caeser_cipher_with_paths.srcs/sources_1/imports/imports/AHB_VGA/dual_port_ram_sync.v
  /home/malak/sites/addproject/caeser_cipher_with_paths/caeser_cipher_with_paths.srcs/sources_1/imports/imports/AHB_VGA/font_rom.v
  /home/malak/sites/addproject/caeser_cipher_with_paths/caeser_cipher_with_paths.srcs/sources_1/imports/sources_1/new/mapto7bitacsii.v
  /home/malak/sites/addproject/caeser_cipher_with_paths/caeser_cipher_with_paths.srcs/sources_1/imports/imports/AHB_VGA/vga_console.v
  /home/malak/sites/addproject/caeser_cipher_with_paths/caeser_cipher_with_paths.srcs/sources_1/imports/imports/AHB_VGA/vga_image.v
  /home/malak/sites/addproject/caeser_cipher_with_paths/caeser_cipher_with_paths.srcs/sources_1/imports/imports/AHB_VGA/vga_sync.v
  /home/malak/sites/addproject/caeser_cipher_with_paths/caeser_cipher_with_paths.srcs/sources_1/imports/sources_1/imports/keyboard/top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/malak/sites/addproject/caeser_cipher_with_paths/caeser_cipher_with_paths.srcs/constrs_1/imports/digilent-xdc-master/Nexys-4-DDR-Master.xdc
set_property used_in_implementation false [get_files /home/malak/sites/addproject/caeser_cipher_with_paths/caeser_cipher_with_paths.srcs/constrs_1/imports/digilent-xdc-master/Nexys-4-DDR-Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
